--- PIZZA SALES PROJECT ---
DROP TABLE IF EXISTS PIZZA_SALES;
CREATE TABLE PIZZA_SALES
(
    pizza_id INTEGER PRIMARY KEY,
    order_id INTEGER ,
    pizza_name_id TEXT ,
    quantity INTEGER ,
    order_date DATE ,
    order_time TIME ,
    unit_price NUMERIC(10,2),
    total_price NUMERIC(10,2) ,
    pizza_size VARCHAR(10),
    pizza_category VARCHAR(50),
    pizza_ingredients TEXT,
    pizza_name TEXT
);
--- Featch all column from sales table ----
SELECT * FROM PIZZA_SALES;

--- Insert data from CSV TO SQL DATABASE ---
COPY (pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_name,pizza_ingredients)
FROM 'D:\SQL Mastery\Practise file\pizza_sales.csv'
DELIMITER ','
CSV HEADER;

---- KPI REQUIREMENTS ----
-- 1) TOTAL REVENUE 
SELECT SUM(TOTAL_PRICE) AS TOTAL_REVENUE
FROM PIZZA_SALES;

--- 2) TOTAL ORDERS 
SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES;

--- 3)  AVERAGE ORDER VALUE 
SELECT CAST(CAST(SUM(TOTAL_PRICE)AS DECIMAL(10,2)) /
CAST(COUNT(DISTINCT ORDER_ID)AS DECIMAL(10,2)) AS DECIMAL(10,2)) AS AVG_ORDER_VALUE
FROM PIZZA_SALES;

--- 4) AVERAGE PIZZAS PER ORDER 
SELECT CAST(CAST(SUM(QUANTITY) AS DECIMAL(10,2))/
CAST(COUNT(DISTINCT ORDER_ID) AS DECIMAL(10,2)) AS DECIMAL(10,2)) AS AVG_PIZZAS_PER_VALUE
FROM PIZZA_SALES;

--- PROBLEM STATEMENT ---
--- 1) SHOW MONTHLY TREND FOR TOTAL REVENUE
SELECT TO_CHAR(ORDER_DATE ,'MONTH') AS MONTH, SUM(TOTAL_PRICE) AS TOTAL_REVENUE
FROM PIZZA_SALES
GROUP BY MONTH
ORDER BY MONTH ASC;

--- 2) SHOW MONTHLY TREND FOR TOTAL ORDER
SELECT TO_CHAR(ORDER_DATE ,'MONTH') AS MONTH, 
COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER
FROM PIZZA_SALES
GROUP BY MONTH
ORDER BY MONTH ASC;

--- 3) SHOW DAILY TREND FOR TOTAL REVENUE
SELECT TO_CHAR(ORDER_DATE ,'DAY') AS ORDER_DAY, SUM(TOTAL_PRICE) AS TOTAL_REVENUE
FROM PIZZA_SALES
GROUP BY TO_CHAR(ORDER_DATE ,'DAY')
ORDER BY TO_CHAR(ORDER_DATE ,'DAY') ASC;

--- 4) SHOW DAILY TREND FOR TOTAL ORDER
SELECT TO_CHAR(ORDER_DATE ,'DAY') AS ORDER_DAY, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER
FROM PIZZA_SALES
GROUP BY TO_CHAR(ORDER_DATE ,'DAY')
ORDER BY TO_CHAR(ORDER_DATE ,'DAY') ASC;

--- 5) % OF SALES BY PIZZA CATEGORY --
SELECT PIZZA_CATEGORY,
CAST(SUM(TOTAL_PRICE) AS NUMERIC(10,2)) AS TOTAL_AMOUNT,
CAST(SUM(TOTAL_PRICE)*100/(SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES) AS NUMERIC(10,2)) AS PCT
FROM PIZZA_SALES
GROUP BY PIZZA_CATEGORY
ORDER BY PIZZA_CATEGORY;

--- 6) % OF SALES BY PIZZA SIZE --
SELECT PIZZA_SIZE,
CAST(SUM(TOTAL_PRICE) AS NUMERIC(10,2)) AS TOTAL_AMOUNT,
CAST(SUM(TOTAL_PRICE)*100/(SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES) AS NUMERIC(10,2)) AS PCT
FROM PIZZA_SALES
GROUP BY PIZZA_SIZE
ORDER BY PIZZA_SIZE;

--- 7) TOTAL PIZZA SOLD BY PIZZA CATEGORY ---
SELECT PIZZA_CATEGORY,
SUM(QUANTITY) AS TOTAL_QUANTITY
FROM PIZZA_SALES
GROUP BY PIZZA_CATEGORY
ORDER BY TOTAL_QUANTITY DESC ;

--- 8) TOP 5 PIZZA BY REVENUE ---
SELECT PIZZA_NAME,
SUM(TOTAL_PRICE) AS TOTAL_AMOUNT
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_AMOUNT DESC
LIMIT 5;

--- 9) BOTTOM 5 PIZZA BY REVENUE ---
SELECT PIZZA_NAME,
SUM(TOTAL_PRICE) AS TOTAL_AMOUNT
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_AMOUNT ASC
LIMIT 5;

--- 10) TOP 5 PIZZA BY QUANTITY ---
SELECT PIZZA_NAME,
SUM(QUANTITY) AS TOTAL_QUANTITY
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_QUANTITY DESC
LIMIT 5

--- 11) BOTTOM 5 PIZZA BY QUANTITY ---
SELECT PIZZA_NAME,
SUM(QUANTITY) AS TOTAL_QUANTITY
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_QUANTITY 
LIMIT 5;

---12) TOP 5 PIZZA WISE TOTAL ORDER --
SELECT PIZZA_NAME,
COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_ORDER DESC
LIMIT 5;

---13) BOTTOM 5 PIZZA WISE TOTAL ORDER --
SELECT PIZZA_NAME,
COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_ORDER 
LIMIT 5;

--- 14) FIND TOP 5 ORDER WISE PIZZA CATEGORY 'Classic' ---
SELECT PIZZA_NAME,
PIZZA_CATEGORY,
COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER
FROM PIZZA_SALES
WHERE PIZZA_CATEGORY = 'Classic'
GROUP BY PIZZA_NAME,PIZZA_CATEGORY
ORDER BY TOTAL_ORDER DESC
LIMIT 5;